In [2]:
d1 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,9,10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,22,23,24]
}

In [3]:
import pandas as pd 

In [4]:
df1 = pd.DataFrame(d1 )

In [5]:
d2 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [6]:
df2 = pd.DataFrame(d2)

In [7]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [8]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [9]:
pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])

/tmp/ipykernel_1400/1864705398.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])


key1  key2_x  key3_x      key4 key2_y  key3_y
0     1     7.0    13.0      19.0      7    13.0
1     2     8.0    14.0      20.0      8    14.0
2     3     9.0    15.0      21.0  kumar    15.0
3     4    10.0    16.0      22.0    NaN     NaN
4     5    11.0    17.0      23.0    NaN     NaN
5  sudh    12.0    18.0      24.0     12    18.0
6     4     NaN     NaN   ineuron     10    16.0
7     5     NaN     NaN  pwskills     11    17.0

In [10]:
pd.merge(df1,df2,how= 'left',on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7    13.0
1      2       8      14   20      2      8    14.0
2      3       9      15   21      3  kumar    15.0
3      4      10      16   22    NaN    NaN     NaN
4      5      11      17   23    NaN    NaN     NaN
5   sudh      12      18   24   sudh     12    18.0

In [11]:
pd.merge(df1,df2,how= 'inner',on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7      13
1      2       8      14   20      2      8      14
2      3       9      15   21      3  kumar      15
3   sudh      12      18   24   sudh     12      18

In [12]:
pd.merge(df1,df2,how= 'inner',on= 'key1')

key1  key2_x  key3_x  key4_x key2_y  key3_y    key4_y
0     1       7      13      19      7      13        19
1     2       8      14      20      8      14        20
2     3       9      15      21  kumar      15        21
3     4      10      16      22     10      16   ineuron
4     5      11      17      23     11      17  pwskills
5  sudh      12      18      24     12      18        24

In [13]:
pd.merge(df1,df2)

key1 key2  key3 key4
0     1    7    13   19
1     2    8    14   20
2  sudh   12    18   24

In [14]:
d11 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}

In [15]:
d12 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [16]:
df11 = pd.DataFrame(d11)

In [17]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [18]:
df12 = pd.DataFrame(d12)

In [19]:
df12

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [20]:
pd.merge(df11, df12 , how = 'left' , left_on = 'a' , right_on='key1')

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  kumar    15        21
3     4  10  16  22     4     10    16   ineuron
4     5  11  17  23     5     11    17  pwskills
5  sudh  12  18  24  sudh     12    18        24

In [21]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [22]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [35]:
d10 = {'key11':[1,2,3,4,5,"sudh"],
      'key21' : [7,8,9,10,11,12],
      'key31':[13,14,15,16,17,18],
      'key41':[19,20,21,22,23,24]
}

In [36]:
d20 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [46]:
df10 = pd.DataFrame(d10 , index = [1,2,3,4,5,6])

In [47]:
df20 = pd.DataFrame(d20, index=[1,2,3,4,5,'sudh'])

In [48]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [49]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  kumar    15        21
4        4     10    16   ineuron
5        5     11    17  pwskills
sudh  sudh     12    18        24

In [50]:
df10.join(df20,how = 'right')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7    13        19
2        2    8.0   14.0   20.0     2      8    14        20
3        3    9.0   15.0   21.0     3  kumar    15        21
4        4   10.0   16.0   22.0     4     10    16   ineuron
5        5   11.0   17.0   23.0     5     11    17  pwskills
sudh   NaN    NaN    NaN    NaN  sudh     12    18        24

In [51]:
df10.join(df20)

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7  13.0        19
2     2      8     14     20    2      8  14.0        20
3     3      9     15     21    3  kumar  15.0        21
4     4     10     16     22    4     10  16.0   ineuron
5     5     11     17     23    5     11  17.0  pwskills
6  sudh     12     18     24  NaN    NaN   NaN       NaN

In [52]:
df10.join(df20 , how = 'outer')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7  13.0        19
2        2    8.0   14.0   20.0     2      8  14.0        20
3        3    9.0   15.0   21.0     3  kumar  15.0        21
4        4   10.0   16.0   22.0     4     10  16.0   ineuron
5        5   11.0   17.0   23.0     5     11  17.0  pwskills
6     sudh   12.0   18.0   24.0   NaN    NaN   NaN       NaN
sudh   NaN    NaN    NaN    NaN  sudh     12  18.0        24

In [53]:
df10.join(df20 , how = 'inner')

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7    13        19
2     2      8     14     20    2      8    14        20
3     3      9     15     21    3  kumar    15        21
4     4     10     16     22    4     10    16   ineuron
5     5     11     17     23    5     11    17  pwskills

In [54]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [55]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  kumar    15        21
4        4     10    16   ineuron
5        5     11    17  pwskills
sudh  sudh     12    18        24

In [57]:
pd.concat([df1,df2] , axis=0)

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3      9    15        21
3     4     10    16        22
4     5     11    17        23
5  sudh     12    18        24
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [60]:
pd.concat([df1,df2] , axis=1)

key1 key2  key3 key4  key1   key2  key3      key4
0     1    7    13   19     1      7    13        19
1     2    8    14   20     2      8    14        20
2     3    9    15   21     3  kumar    15        21
3     4   10    16   22     4     10    16   ineuron
4     5   11    17   23     5     11    17  pwskills
5  sudh   12    18   24  sudh     12    18        24

In [61]:
import numpy as np 

In [62]:
l = [1,2,3,4,4]

In [64]:
type(l)

list

In [66]:
a = np.array(l)

In [67]:
type(a)

numpy.ndarray

In [68]:
a

array([1, 2, 3, 4, 4])

In [73]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [74]:
a1


array([[1, 2, 3],
       [3, 4, 5]])

In [75]:
a2 = np.array([[[1,2,3] , [4,.5,6]]])

In [76]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [77]:
a

array([1, 2, 3, 4, 4])

In [78]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [79]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [80]:
a.ndim

1

In [81]:
a1.ndim


2

In [82]:
a2.ndim

3

In [83]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [84]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [85]:
a3.ndim

3