In [2]:
d1 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,9,10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,22,23,24]
}

In [3]:
import pandas as pd 

In [4]:
df1 = pd.DataFrame(d1 )

In [5]:
d2 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [6]:
df2 = pd.DataFrame(d2)

In [7]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [8]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [9]:
pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])

/tmp/ipykernel_1400/1864705398.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how= 'outer',on= ['key4','key1'])


key1  key2_x  key3_x      key4 key2_y  key3_y
0     1     7.0    13.0      19.0      7    13.0
1     2     8.0    14.0      20.0      8    14.0
2     3     9.0    15.0      21.0  kumar    15.0
3     4    10.0    16.0      22.0    NaN     NaN
4     5    11.0    17.0      23.0    NaN     NaN
5  sudh    12.0    18.0      24.0     12    18.0
6     4     NaN     NaN   ineuron     10    16.0
7     5     NaN     NaN  pwskills     11    17.0

In [10]:
pd.merge(df1,df2,how= 'left',on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7    13.0
1      2       8      14   20      2      8    14.0
2      3       9      15   21      3  kumar    15.0
3      4      10      16   22    NaN    NaN     NaN
4      5      11      17   23    NaN    NaN     NaN
5   sudh      12      18   24   sudh     12    18.0

In [11]:
pd.merge(df1,df2,how= 'inner',on= 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y  key3_y
0      1       7      13   19      1      7      13
1      2       8      14   20      2      8      14
2      3       9      15   21      3  kumar      15
3   sudh      12      18   24   sudh     12      18

In [12]:
pd.merge(df1,df2,how= 'inner',on= 'key1')

key1  key2_x  key3_x  key4_x key2_y  key3_y    key4_y
0     1       7      13      19      7      13        19
1     2       8      14      20      8      14        20
2     3       9      15      21  kumar      15        21
3     4      10      16      22     10      16   ineuron
4     5      11      17      23     11      17  pwskills
5  sudh      12      18      24     12      18        24

In [13]:
pd.merge(df1,df2)

key1 key2  key3 key4
0     1    7    13   19
1     2    8    14   20
2  sudh   12    18   24

In [14]:
d11 = {'a':[1,2,3,4,5,"sudh"],
      'b' : [7,8,9,10,11,12],
      'c':[13,14,15,16,17,18],
      'd':[19,20,21,22,23,24]
}

In [15]:
d12 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [16]:
df11 = pd.DataFrame(d11)

In [17]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [18]:
df12 = pd.DataFrame(d12)

In [19]:
df12

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [20]:
pd.merge(df11, df12 , how = 'left' , left_on = 'a' , right_on='key1')

a   b   c   d  key1   key2  key3      key4
0     1   7  13  19     1      7    13        19
1     2   8  14  20     2      8    14        20
2     3   9  15  21     3  kumar    15        21
3     4  10  16  22     4     10    16   ineuron
4     5  11  17  23     5     11    17  pwskills
5  sudh  12  18  24  sudh     12    18        24

In [21]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5  sudh    12    18    24

In [22]:
df2

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [35]:
d10 = {'key11':[1,2,3,4,5,"sudh"],
      'key21' : [7,8,9,10,11,12],
      'key31':[13,14,15,16,17,18],
      'key41':[19,20,21,22,23,24]
}

In [36]:
d20 = {'key1':[1,2,3,4,5,"sudh"],
      'key2' : [7,8,"kumar",10,11,12],
      'key3':[13,14,15,16,17,18],
      'key4':[19,20,21,"ineuron","pwskills",24]
}

In [46]:
df10 = pd.DataFrame(d10 , index = [1,2,3,4,5,6])

In [47]:
df20 = pd.DataFrame(d20, index=[1,2,3,4,5,'sudh'])

In [48]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [49]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  kumar    15        21
4        4     10    16   ineuron
5        5     11    17  pwskills
sudh  sudh     12    18        24

In [50]:
df10.join(df20,how = 'right')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7    13        19
2        2    8.0   14.0   20.0     2      8    14        20
3        3    9.0   15.0   21.0     3  kumar    15        21
4        4   10.0   16.0   22.0     4     10    16   ineuron
5        5   11.0   17.0   23.0     5     11    17  pwskills
sudh   NaN    NaN    NaN    NaN  sudh     12    18        24

In [51]:
df10.join(df20)

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7  13.0        19
2     2      8     14     20    2      8  14.0        20
3     3      9     15     21    3  kumar  15.0        21
4     4     10     16     22    4     10  16.0   ineuron
5     5     11     17     23    5     11  17.0  pwskills
6  sudh     12     18     24  NaN    NaN   NaN       NaN

In [52]:
df10.join(df20 , how = 'outer')

key11  key21  key31  key41  key1   key2  key3      key4
1        1    7.0   13.0   19.0     1      7  13.0        19
2        2    8.0   14.0   20.0     2      8  14.0        20
3        3    9.0   15.0   21.0     3  kumar  15.0        21
4        4   10.0   16.0   22.0     4     10  16.0   ineuron
5        5   11.0   17.0   23.0     5     11  17.0  pwskills
6     sudh   12.0   18.0   24.0   NaN    NaN   NaN       NaN
sudh   NaN    NaN    NaN    NaN  sudh     12  18.0        24

In [53]:
df10.join(df20 , how = 'inner')

key11  key21  key31  key41 key1   key2  key3      key4
1     1      7     13     19    1      7    13        19
2     2      8     14     20    2      8    14        20
3     3      9     15     21    3  kumar    15        21
4     4     10     16     22    4     10    16   ineuron
5     5     11     17     23    5     11    17  pwskills

In [54]:
df10

key11  key21  key31  key41
1     1      7     13     19
2     2      8     14     20
3     3      9     15     21
4     4     10     16     22
5     5     11     17     23
6  sudh     12     18     24

In [55]:
df20

key1   key2  key3      key4
1        1      7    13        19
2        2      8    14        20
3        3  kumar    15        21
4        4     10    16   ineuron
5        5     11    17  pwskills
sudh  sudh     12    18        24

In [57]:
pd.concat([df1,df2] , axis=0)

key1   key2  key3      key4
0     1      7    13        19
1     2      8    14        20
2     3      9    15        21
3     4     10    16        22
4     5     11    17        23
5  sudh     12    18        24
0     1      7    13        19
1     2      8    14        20
2     3  kumar    15        21
3     4     10    16   ineuron
4     5     11    17  pwskills
5  sudh     12    18        24

In [60]:
pd.concat([df1,df2] , axis=1)

key1 key2  key3 key4  key1   key2  key3      key4
0     1    7    13   19     1      7    13        19
1     2    8    14   20     2      8    14        20
2     3    9    15   21     3  kumar    15        21
3     4   10    16   22     4     10    16   ineuron
4     5   11    17   23     5     11    17  pwskills
5  sudh   12    18   24  sudh     12    18        24

In [61]:
import numpy as np 

In [62]:
l = [1,2,3,4,4]

In [64]:
type(l)

list

In [66]:
a = np.array(l)

In [67]:
type(a)

numpy.ndarray

In [68]:
a

array([1, 2, 3, 4, 4])

In [73]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [74]:
a1


array([[1, 2, 3],
       [3, 4, 5]])

In [75]:
a2 = np.array([[[1,2,3] , [4,.5,6]]])

In [76]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [77]:
a

array([1, 2, 3, 4, 4])

In [78]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [79]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [80]:
a.ndim

1

In [81]:
a1.ndim


2

In [82]:
a2.ndim

3

In [83]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [84]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [85]:
a3.ndim

3

In [86]:
l = [1,2,3,4]

In [90]:
a = np.asarray(l)

In [89]:
m = np.matrix(l)

In [93]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [91]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [92]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [94]:
a

array([1, 2, 3, 4])

In [95]:
a1 = a 

In [96]:
a1

array([1, 2, 3, 4])

In [97]:
a

array([1, 2, 3, 4])

In [98]:
a

array([1, 2, 3, 4])

In [100]:
a[0] = 10

In [101]:
a

array([10,  2,  3,  4])

In [102]:
a1

array([10,  2,  3,  4])

In [104]:
a1[3] = 50

In [105]:
a1

array([10,  2,  3, 50])

In [106]:
a

array([10,  2,  3, 50])

In [107]:
a2 = np.copy(a)

In [108]:
a2

array([10,  2,  3, 50])

In [111]:
a2[2] = 30

In [112]:
a2

array([10,  2, 30, 50])

In [113]:
a

array([10,  2,  3, 50])

In [114]:
np.fromfunction(lambda i,j : i==j , (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [116]:
np.fromfunction(lambda i,j: i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [118]:
np.random.rand(2,3,2)

array([[[0.8537019 , 0.89559976],
        [0.69730849, 0.65386202],
        [0.43384847, 0.47219106]],

       [[0.11591441, 0.5194264 ],
        [0.04490197, 0.73227366],
        [0.2114251 , 0.7732894 ]]])

In [119]:
np.random.rand(2,3,2,2)

array([[[[0.53725569, 0.20683012],
         [0.86591778, 0.45198326]],

        [[0.80552188, 0.32802758],
         [0.21144657, 0.65774064]],

        [[0.22610232, 0.45318178],
         [0.60987073, 0.59909623]]],


       [[[0.28732243, 0.3049974 ],
         [0.25456288, 0.37661516]],

        [[0.91435676, 0.30877497],
         [0.35806469, 0.08779498]],

        [[0.1470572 , 0.80567483],
         [0.33217116, 0.97522411]]]])

In [123]:
np.random.rand(3,4,5)

array([[[9.09677029e-01, 1.51764787e-01, 5.54673202e-01, 5.20975075e-01,
         1.89883414e-01],
        [7.53923727e-01, 9.40966362e-01, 7.88123405e-01, 9.08953572e-01,
         9.64805229e-01],
        [4.00655124e-01, 1.75199657e-01, 4.57227487e-01, 5.17727882e-01,
         2.86751041e-01],
        [1.30429473e-01, 9.02009153e-01, 9.11345542e-02, 4.89073768e-01,
         5.03991486e-02]],

       [[6.86026889e-01, 2.89092687e-01, 9.89068408e-01, 8.89560944e-04,
         3.29450171e-01],
        [2.90054731e-01, 9.99508005e-01, 9.46035196e-01, 4.19070101e-01,
         9.45084024e-01],
        [4.62420004e-01, 1.88486694e-01, 4.14268952e-01, 7.85958823e-01,
         5.25020759e-02],
        [6.35797430e-01, 8.16778744e-01, 7.61395700e-01, 7.18578055e-01,
         2.76044227e-01]],

       [[1.44572781e-02, 9.19394486e-02, 4.45699994e-01, 7.56659750e-01,
         9.02694336e-02],
        [2.70860822e-01, 1.57507607e-01, 3.84106908e-01, 7.97338456e-01,
         5.02090497e-01],
      

In [130]:
d = np.random.randn(3,4)

In [131]:
pd.DataFrame(d)

0         1         2         3
0 -0.976138 -0.805954  1.007809 -0.089897
1  0.212211 -0.893465 -0.005551  1.240048
2  0.367181 -1.252373  1.449878 -0.699765

In [132]:
d1=np.random.randint(0,10,(4,4,2))

In [133]:
d1

array([[[0, 3],
        [2, 4],
        [2, 1],
        [2, 4]],

       [[9, 5],
        [0, 7],
        [9, 7],
        [4, 1]],

       [[6, 6],
        [6, 3],
        [8, 8],
        [5, 4]],

       [[7, 9],
        [5, 1],
        [0, 8],
        [4, 4]]])

In [135]:
d1.reshape(16,2)

array([[0, 3],
       [2, 4],
       [2, 1],
       [2, 4],
       [9, 5],
       [0, 7],
       [9, 7],
       [4, 1],
       [6, 6],
       [6, 3],
       [8, 8],
       [5, 4],
       [7, 9],
       [5, 1],
       [0, 8],
       [4, 4]])

In [136]:
d1.reshape(8,4)

array([[0, 3, 2, 4],
       [2, 1, 2, 4],
       [9, 5, 0, 7],
       [9, 7, 4, 1],
       [6, 6, 6, 3],
       [8, 8, 5, 4],
       [7, 9, 5, 1],
       [0, 8, 4, 4]])

In [145]:
pd.DataFrame(d1.reshape(32,-1987987))

0
0   0
1   3
2   2
3   4
4   2
5   1
6   2
7   4
8   9
9   5
10  0
11  7
12  9
13  7
14  4
15  1
16  6
17  6
18  6
19  3
20  8
21  8
22  5
23  4
24  7
25  9
26  5
27  1
28  0
29  8
30  4
31  4

In [134]:
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)